quotescraper/noteapp/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('authors/<int:author_id>/', views.author_detail, name='author_detail'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('tag/<str:tag_name>/', views.selected_tag, name='selected_tag'),
]

quotescraper/notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

quotescraper/users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotescraper/noteapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    fullname = models.CharField()
    born_date = models.CharField()
    born_location = models.CharField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

quotescraper/noteapp/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, DateInput, ModelMultipleChoiceField, SelectMultiple, ModelChoiceField, Select
from .models import Author, Quote, Tag


class RegisterAuthor(ModelForm):
    fullname = CharField(max_length=100,
                         required=True,
                         widget=TextInput(attrs={'class': 'form-control'}))

    born_date = DateField(widget=DateInput(attrs={'class': 'form-control'}))

    born_location = CharField(max_length=150,
                              required=True,
                              widget=TextInput(attrs={'class': 'form-control'}))

    description = CharField(required=True, widget=TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class RegisterQuote(ModelForm):
    quote = CharField(required=True,
                      widget=TextInput(attrs={'class': 'form-control'}))

    tags = ModelChoiceField(queryset=Tag.objects.all().order_by('name'), empty_label="(Nothing)",
                                    widget=Select(attrs={"class": "form-select"}))

    author = ModelChoiceField(queryset=Author.objects.all().order_by('fullname'), empty_label="(Nothing)",
                              widget=Select(attrs={"class": "form-select"}))

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

    def __init__(self, *args, **kwargs):
        super(RegisterQuote, self).__init__(*args, **kwargs)
        self.fields['tags'].queryset = Tag.objects.all().order_by('name')
        self.fields['tags'].label_from_instance = lambda obj: obj.name
        self.fields['author'].queryset = Author.objects.all().order_by('fullname')
        self.fields['author'].label_from_instance = lambda obj: obj.fullname


class RegisterTag(ModelForm):
    name = CharField(min_length=3,
                     max_length=50,
                     required=True,
                     widget=TextInput(attrs={"class": "form-control"}))

    def __str__(self):
        return self.name

    class Meta:
        model = Tag
        fields = ['name']

quotescraper/noteapp/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Count
from django.contrib.auth.decorators import login_required

from .utils import get_mongodb
from .models import Tag, Author, Quote
from .forms import RegisterAuthor, RegisterQuote, RegisterTag


popular_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
popular_tags = [(tag, 2.75 * tag.num_quotes) for tag in popular_tags]


def main(request, page=1):
    context = {}
    # db = get_mongodb()
    # quotes = db.quotes.find()
    quotes = Quote.objects.all()

    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)

    context['popular_tags'] = popular_tags
    context['quotes'] = quotes_on_page
    return render(request, 'quotes/index.html', context=context)


def author_detail(request, author_id):
    author = Author.objects.get(pk=author_id)
    return render(request, 'quotes/author.html', context={'author': author})


def selected_tag(request, tag_name, page=1):
    tag = Tag.objects.get(name=tag_name)
    quotes = Quote.objects.filter(tags=tag)
    context = {
        'tag': tag,
        'quotes': quotes,
        'popular_tags': popular_tags,
    }
    return render(request, 'quotes/tags.html', context=context)


@login_required
def add_author(request):
    if request.method == 'POST':
        form = RegisterAuthor(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/add_author.html', context={'form': form})

    return render(request, 'quotes/add_author.html', context={'form': RegisterAuthor()})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = RegisterQuote(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.user = request.user
            new_quote.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/add_quote.html', context={'form': form})

    return render(request, 'quotes/add_quote.html', context={'form': RegisterQuote()})

quotescraper/noteapp/templates/quotes/add_author.html
{% extends './base.html' %}

{% block content %}

<div>
    <h2>Add Author</h2>
</div>
<form action="{% url 'quotes:add_author' %}" method="post">
    {% csrf_token %}
    <div class="row mb-3">
        <div class="form-group col-xs-3">
            <label>Fullname: <br>
                {{ form.fullname }}
            </label>
            <span>{{ form.errors.fullname }}</span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="form-group col-xs-3">
            <label>Born date: <br>
                {{ form.born_date }}
            </label>
            <span>{{ form.errors.born_date }}</span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="form-group col-xs-3">
            <label>Born location: <br>
                {{ form.born_location }}
            </label>
            <span>{{ form.errors.born_location }}</span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="form-group col-xs-3">
            <label>Description: <br>
                {{ form.description }}
            </label>
            <span>{{ form.errors.description }}</span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>

</form>

{% endblock %}

quotescraper/noteapp/templates/quotes/add_quote.html
{% extends './base.html' %}

{% block content %}

<div>
    <h2>Add Author</h2>
</div>
<form action="{% url 'quotes:add_quote' %}" method="post">
    {% csrf_token %}
    <div class="row mb-3">
        <div class="form-group col-xs-3">
            <label>Quote: <br>
                {{ form.quote }}
            </label>
            <span>{{ form.errors.quote }}</span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="form-group col-xs-3">
            <label>Tags: <br>
                {{ form.tags }}
            </label>
            <span>{{ form.errors.tags }}</span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="form-group col-xs-3">
            <label>Author: <br>
                {{ form.author }}
            </label>
            <span>{{ form.errors.author }}</span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>

</form>

{% endblock %}

quotescraper/noteapp/templates/quotes/add_tag.html
{% extends './base.html' %}

{% block content %}

<div>
    <h2>Add Author</h2>
</div>
<form action="{% url 'quotes:add_quote' %}" method="post">
    {% csrf_token %}
    <div class="row mb-3">
        <div class="form-group col-xs-3">
            <label>Quote: <br>
                {{ form.quote }}
            </label>
            <span>{{ form.errors.quote }}</span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="form-group col-xs-3">
            <label>Tags: <br>
                {{ form.tags }}
            </label>
            <span>{{ form.errors.tags }}</span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="form-group col-xs-3">
            <label>Author: <br>
                {{ form.author }}
            </label>
            <span>{{ form.errors.author }}</span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>

</form>

{% endblock %}

quotescraper/noteapp/templates/quotes/author.html
{% extends 'quotes/base.html' %}
{% block content %}
<h1>{{ author.fullname }}</h1>
<p><strong>Date of birth:</strong> {{ author.born_date }} {{ author.born_location }}</p>
<p><strong>Description:</strong> {{ author.description }}</p>
{% endblock %}

quotescraper/noteapp/templates/quotes/base.html
<!doctype html>
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/modern-normalize/1.0.0/modern-normalize.min.css"/>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'quotes/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"></script>
    
    <title>Quotes</title>
</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8 pt-3 mb-3">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                {% if user.is_authenticated %}
                <p>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-success">Add quote</a>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-success">Add author</a>
                    Welcome <b>{{ user.username }}</b>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                </p>
                {% else %}
                <p>
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">Sign Up</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Sign In</a>
                </p>
                {% endif %}

            </div>
        </div>
        {% block content %} {% endblock content %}
    </div>

</body>
</html>

quotescraper/noteapp/templates/quotes/index.html
{% extends './base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{ quote.quote }}</span>
            <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small>
                <a href="{% url 'quotes:author_detail' quote.author.id %}" style="text-decoration: none;">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" style="text-decoration: none;" href="/tag/{{ tag.name }}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span>
                    </a>
                </li>

            </ul>
        </nav>
    </div>
    <div class="col-md-3 tags-box">
        {% include 'quotes/top_tags.html' %}
    </div>
</div>
{% endblock %}

quotescraper/noteapp/templates/quotes/tags.html
{% extends 'quotes/base.html' %}
{% block content %}

<h3>Viewing tag: <a href="/tag/{{ tag.name }}" style="text-decoration: none;">{{ tag.name }}</a></h3>
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{ quote.quote }}</span>
            <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small>
                <a href="{% url 'quotes:author_detail' quote.author.id %}" style="text-decoration: none;">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" style="text-decoration: none;" href="/tag/{{ tag.name }}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-3 tags-box">
        {% include 'quotes/top_tags.html' %}
    </div>
</div>

{% endblock %}

quotescraper/noteapp/templates/quotes/top_tags.html
{% block content %}
<h2>Top Ten tags</h2>
{% for tag, size in popular_tags %}
<span class="tag-item pt-1" style="display: block;">
    <a class="tag" style="font-size: {{ size }}px; text-decoration: none;" href="/tag/{{ tag.name }}">
        {{ tag.name }}
    </a>
</span>
{% endfor %}
{% endblock %}